// Gen 1-5 (bereits vorhanden) + Gen 6-9
const POKEMON_LIST_GEN6_9 = [
  // Gen 6 (Kalos) - #650-721
  "Igamaro","Igastan","Brigaron","Fynx","Rutena","Fennexis","Froxy","Amphizel","Quajutsu",
  "Scoppel","Grebbit","Dartiri","Dartignis","Fiaro","Purmel","Puponcho","Wommel","Honweisel",
  "Pachirisu","Bamelin","Bojelin","Kikugi","Kinoso","Schalellos","Gastrodon","Ambidiffel",
  "Driftlon","Drifzepeli","Haspiror","Schlapor","Traunmagil","Kramshef","Charmian",
  "Shnurgarst","Klingplim","Skunkapuh","Skuntank","Bronzel","Bronzong","Mobai","Pantimimi",
  "Wonneira","Plaudagei","Kryppuk","Kaumalat","Knarksel","Knakrack","Mampfaxo","Riolu",
  "Lucario","Hippopotas","Hippoterus","Pionskora","Piondragi","Glibunkel","Toxiquak",
  "Venuflibis","Finneon","Lumineon","Mantirps","Shnebedeck","Rexblisar","Snibunna",
  "Magnezone","Schlurplek","Rihornior","Tangoloss","Elevoltek","Magbrant","Togekiss",
  "Yanmega","Folipurba","Glaziola","Skorgro","Mamutel","Porygon-Z","Galagladi","Voluminas",
  "Zwirrfinst","Frosdedje","Rotom","Selfe","Vesprit","Tobutz","Dialga","Palkia","Heatran",
  "Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus",
  "Victini","Serpifeu","Efoserp","Serpiroyal","Floink","Ferkokel","Flambirex","Ottaro",
  "Zwottronin","Admurai","Nagelotz","Kukmarda","Yorkleff","Terribark","Bissbark","Felilou",
  "Kleoparda","Vegimak","Vegichita","Grillmak","Grillchita","Sodamak","Sodachita","Somniam",
  "Somnivora","Dusselgurr","Navitaub","Fasasnob","Elezeba","Zebritz","Kiesling","Sedimantur",
  "Brockoloss","Fleknoil","Fletiamo","Rotomurf","Stalobor","Ohrdoch","Praktibalk","Strepoli",
  "Meistagrif","Schallquap","Mebrana","Branawarz","Jiutesto","Karadonis","Strawickl",
  "Folikon","Matrifol","Toxiped","Rollum","Cerapendra","Waumboll","Elfun","Lilminip",
  "Dressella","Barschuft","Ganovil","Rokkaiman","Rabigator","Flampion","Flampivian",
  "Maracamba","Lithomith","Castellith","Zurrokex","Irokex","Symvolara","Makabaja",
  "Echnatoll","Galapaflos","Karippas","Flapteryx","Aeropteryx","Unratütox","Deponitox",
  "Zorua","Zoroark","Picochilla","Chillabell","Mollimorba","Hypnomorba","Morbitesse",
  "Monozyto","Mitodos","Zytomega","Piccolente","Swaroness","Gelatini","Gelatroppo",
  "Gelatwino","Sesokitz","Kronjuwild","Emolga","Laukaps","Cavalanzas","Tarnpignon",
  "Hutsassa","Quabbel","Apoquallyp","Mamolida","Wattzapf","Voltula","Kastadur",
  "Tentantel","Klikk","Kliklak","Klikdiklak","Zapplardin","Zapplalek","Zapplarang",
  "Pygraulon","Megalon","Lichtel","Laternecto","Skelabra","Milza","Sharfax","Maxax",
  "Petznief","Siberio","Frigometri","Schnuthelm","Hydragil","Flunschlik","Lin-Fu",
  "Wie-Shu","Shardrago","Golbit","Golgantes","Gladiantri","Caesurio","Bisofank",
  "Geronimatz","Washakwil","Skallyk","Grypheldis","Furnifraß","Fermicula","Kapuno",
  "Duodino","Trikephalo","Ignivor","Ramoth","Kobalium","Terrakium","Viridium","Boreos",
  "Voltolos","Reshiram","Zekrom","Demeteros","Kyurem","Keldeo","Meloetta","Genesect",
  
  // Gen 6 (ab hier korrekt fortgesetzt)
  "Igamaro","Igastan","Brigaron","Fynx","Rutena","Fennexis","Froxy","Amphizel","Quajutsu",
  "Scoppel","Grebbit","Dartiri","Dartignis","Fiaro","Purmel","Puponcho","Wommel",
  "Honweisel","Pachirisu","Bamelin","Bojelin","Kikugi","Kinoso","Schalellos","Gastrodon",
  "Ambidiffel","Driftlon","Drifzepeli","Haspiror","Schlapor","Traunmagil","Kramshef",
  "Charmian","Shnurgarst","Klingplim","Skunkapuh","Skuntank","Bronzel","Bronzong",
  "Mobai","Pantimimi","Wonneira","Plaudagei","Kryppuk","Kaumalat","Knarksel","Knakrack",
  "Mampfaxo","Riolu","Lucario","Hippopotas","Hippoterus","Pionskora","Piondragi",
  "Glibunkel","Toxiquak","Venuflibis","Finneon","Lumineon","Mantirps","Shnebedeck",
  "Rexblisar","Snibunna","Magnezone","Schlurplek","Rihornior","Tangoloss","Elevoltek",
  "Magbrant","Togekiss","Yanmega","Folipurba","Glaziola","Skorgro","Mamutel","Porygon-Z",
  "Galagladi","Voluminas","Zwirrfinst","Frosdedje","Rotom","Selfe","Vesprit","Tobutz",
  "Dialga","Palkia","Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy",
  "Darkrai","Shaymin","Arceus"
];
